// [BACKEND · Express] src/Storage/diskStorage.js
// LOCAL DEVELOPMENT ONLY: keeps uploaded files in a folder on this computer so the app can be tried without
// an AWS account. A server's disk is erased on redeploy, so production must use S3 (see Storage/index.js).
const fs = require('fs');
const path = require('path');

function createDiskStorage({ rootDir }) {
  const root = path.resolve(rootDir);

  // Keys are generated by the server, but check anyway: a key may never point outside the upload folder.
  const resolve = (key) => {
    const full = path.resolve(root, key);
    if (full !== root && !full.startsWith(root + path.sep)) throw new Error('Invalid storage key.');
    return full;
  };

  return {
    provider: 'disk',
    bucket: null,
    async put({ key, body }) {
      const file = resolve(key);
      await fs.promises.mkdir(path.dirname(file), { recursive: true });
      await fs.promises.writeFile(file, body);
    },
    async getStream(key) {
      const file = resolve(key);
      await fs.promises.access(file); // throws if missing, before any response headers are sent
      return fs.createReadStream(file);
    },
    async remove(key) {
      await fs.promises.rm(resolve(key), { force: true });
    },
    urlFor(key) {
      return `disk://${key}`;
    },
  };
}

module.exports = { createDiskStorage };
